name: iOS Enviroment Setup
description: "iOS Enviroment Setup"
inputs:
  ios-download-build:
    required: true
  ios-model:
    required: true
  ios-version:
    required: true
runs:
  using: "composite"
  steps:
    - name: Install Appium
      run: |
        npm i --location=global appium
        appium driver install xcuitest
      shell: bash

    - name: Set Up Xcode
      run: sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
      shell: bash

    - name: Verify Xcode Installation
      run: xcodebuild -version -sdk
      shell: bash

    - name: Check Available Simulators
      run: xcrun simctl list devices
      shell: bash

    - name: Download and Extract iOS Build
      run: |
        wget -O ios_build.tar.gz ${{ inputs.ios-download-build }}
        mkdir -p App
        mv ios_build.tar.gz App/
        cd App
        tar -xzf ios_build.tar.gz
      shell: bash

    - name: Set Up iOS Simulator
      id: setup-simulator
      uses: futureware-tech/simulator-action@v3
      with:
        model: "${{ inputs.ios-model }}"
        os_version: ${{ inputs.ios-version }}

    - name: Set Environment Variables for Simulator
      id: set-env-simulator
      run: echo "SIMULATOR_UDID=${{ steps.setup-simulator.outputs.udid }}" >> $GITHUB_ENV
      shell: bash
