name: iOS Enviroment Setup
description: "iOS Enviroment Setup"
inputs:
  ios-download-build:
    required: true
  ios-model:
    required: true
  ios-version:
    required: true
runs:
  using: "composite"
  steps:
    - name: 🛠️ Setup Expo
      uses: expo/expo-github-action@v8
      with:
        expo-version: latest
        eas-version: latest
        token: ${{ secrets.EXPO_TOKEN }}

    - name: Install Appium
      run: |
        npm i --location=global appium
        appium driver install xcuitest
      shell: bash

    - name: Set Up Xcode
      run: sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
      shell: bash

    - name: Verify Xcode Installation
      run: xcodebuild -version -sdk
      shell: bash

    - name: Check Available Simulators
      run: xcrun simctl list devices
      shell: bash

    - name: Checkout Application Code
      uses: actions/checkout@v4
      with:
        repository: huynhlan21/test
        ref: build
        path: App

    - name: Build for iOS Similators
      run: |
        cd App
        eas build --profile simulator --platform ios
        eas build:list --json --non-interactive --limit=1 --platform=ios | jq -r .[0].artifacts.buildUrl
        echo "ios-download-build=$(eas build:list --json --non-interactive --limit=1 --platform=ios | jq -r .[0].artifacts.buildUrl)" >> $GITHUB_ENV

    - name: Download and Extract iOS Build
      run: |
        wget -O ios_build.tar.gz ${{ env.ios-download-build }}
        # mkdir -p App
        mv ios_build.tar.gz App/
        cd App
        tar -xzf ios_build.tar.gz
      shell: bash

    - name: Set Up iOS Simulator
      id: setup-simulator
      uses: futureware-tech/simulator-action@v3
      with:
        model: "${{ inputs.ios-model }}"
        os_version: ${{ inputs.ios-version }}

    - name: Set Environment Variables for Simulator
      id: set-env-simulator
      run: echo "SIMULATOR_UDID=${{ steps.setup-simulator.outputs.udid }}" >> $GITHUB_ENV
      shell: bash
