name: Enviroment Setup
description: "Enviroment Setup"
runs:
  using: "composite"
  steps:
    - name: Set Up Homebrew
      uses: Homebrew/actions/setup-homebrew@master

    - name: Set Up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.12.0"

    - name: Install Dependencies
      run: |
        python3 -m venv venv
        source venv/bin/activate
        pip install -r requirements.txt
      shell: bash

    - name: 🛠️ Setup Expo
      uses: expo/expo-github-action@v8
      with:
        expo-version: latest
        eas-version: latest
        token: ${{ secrets.EXPO_TOKEN }}
