name: Enviroment Setup
description: "Enviroment Setup"
runs:
  using: "composite"
  steps:
    - name: Set Up Homebrew
      uses: Homebrew/actions/setup-homebrew@master

    - name: Set Up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.12.0"

    # - name: Active venv
    #   run: |
    #     python3 -m venv venv
    #     source venv/bin/activate
    #   shell: bash

    - name: Install Dependencies
      run: |
        pip install -r requirements.txt
      shell: bash
