name: Android Automation

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Android Automation Test
    runs-on: macos-latest
    # strategy:
    #   matrix:
    #     api-level: [29, 30, 31, 32, 33]
    env:
      api-level: 33
    steps:
      - name: Checkout Automation Code
        uses: actions/checkout@v4

      - name: Environment Setup
        uses: ./.github/actions/setup

      - name: Install Appium and Android Platform
        run: |
          npm i --location=global appium
          appium driver install uiautomator2
          brew update
          brew install android-platform-tools

      - name: Set Up Environment Variables
        run: |
          echo 'export ANDROID_HOME=~/Library/Android/sdk' >> $HOME/.bashrc
          echo 'export PATH=$PATH:$ANDROID_HOME/tools/bin' >> $HOME/.bashrc
          echo 'export PATH=$PATH:$ANDROID_HOME/platform-tools' >> $HOME/.bashrc
          echo 'export PATH=$PATH:/usr/local/lib/android/sdk/platform-tools' >> $HOME/.bashrc
          source $HOME/.bashrc

      - name: Update Android SDK
        run: source $HOME/.bashrc && $ANDROID_HOME/tools/bin/sdkmanager --update

      - name: Accept Android Licenses
        run: yes | source $HOME/.bashrc && $ANDROID_HOME/tools/bin/sdkmanager --licenses

      - name: Download APK File
        run: |
          wget -O application.apk ${{ vars.ANDROID_BUILD_URL }}
          mkdir -p App
          mv application.apk App/

      - name: AVD Cache
        uses: actions/cache@v3
        id: avd-cache
        with:
          path: |
            ~/.android/avd/*
            ~/.android/adb*
          key: avd-29

      - name: Start Appium Server
        run: appium &

      - name: Create AVD and Run Tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          # api-level: ${{ matrix.api-level }}
          api-level: ${{ env.api-level }}
          arch: x86_64
          force-avd-creation: false
          emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: false
          script: |
            adb devices
            adb install -r App/application.apk
            robot -d Reports/${{ env.api-level }} --loglevel TRACE UiTests/TestSuite_android.robot

      - name: Archive Test Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Android Automation (${{ env.api-level }}) Reports
          path: Reports/${{ env.api-level }}

      - name: Stop Appium Server
        run: pkill -f appium

      - name: Clean up
        run: |
          rm -rf /tmp/appium*
          rm -rf ~/.android/avd/*
          rm -rf ~/.android/adb*
          rm -f App/application.apk
          rm -rf venv
